### ISSUE TITLE
Ask questions about HDV

### ISSUE THREAD

**Issue by zhangjiajunjiajun** [atpham88/HDV#2]
Hi,I have some questions about this file that I would like you to help solve, thank you very much.
Traceback (most recent call last):
  File "D:\HDV-main\Get Solar CFs\get_solar_cf.py", line 408, in <module>
    main()
  File "D:\HDV-main\Get Solar CFs\get_solar_cf.py", line 373, in main
    solarGen['{lat} {lon}'.format(lat=lat, lon=lon)] = getSolarCF(solarResourceData)
  File "D:\HDV-main\Get Solar CFs\get_solar_cf.py", line 125, in getSolarCF
    s = pv.default("PVWattsNone")
Exception: Default configuration by that name was not found.

**Comment by atpham88** [comment]
Hello, can you please change

`import PySAM.Pvwattsv7 as pv`

to

`import PySAM.Pvwattsv8 as pv`

and rerun?

**Comment by zhangjiajunjiajun** [comment]
Thank you very much for your reply, following your suggestion, this program runs as follows：


The result has been looping, is this result correct?And I also have two questions, firstly, what are the specific functions of get_solar_cf.py and clean_solar_cf.py? Secondly, are these two programs directly related to the operation of the main.py?This question is because these two programs are not working now, and I get zero solar-related data when running the main.py, I am very confused about this, I hope to get your help, thank you again.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "atpham88/HDV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 凌晨3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [atpham88/HDV] Ask questions about HDV (Issue #2)





 
Hello, can you please change
 
import PySAM.Pvwattsv7 as pv
 
to
 
import PySAM.Pvwattsv8 as pv
 
and rerun?

**Comment by atpham88** [comment]
The main.py does not call get_solar_cf.py and clean_solar_cf.py. Those two functions are to run separately to get data inputs  (solar_CF_case1.xlsx, solar_CF_case2.xlsx,solar_CF_case3.xlsx) for get_solar_data.py which is called by main.py.

Since I already provided inputs for get_solar_data.py, you do not have to run get_solar_cf and clean_solar_cf in order to run main, unless you want to collect solar data for a different year for example.

**Comment by zhangjiajunjiajun** [comment]
I&nbsp;am&nbsp;very&nbsp;sorry&nbsp;to&nbsp;bother&nbsp;you&nbsp;again.&nbsp;I&nbsp;met&nbsp;a&nbsp;problem,&nbsp;as&nbsp;shown&nbsp;in&nbsp;the&nbsp;picture&nbsp;below.&nbsp;


It marked&nbsp;red&nbsp;line&nbsp;below,&nbsp;indicating&nbsp;no&nbsp;definition. How&nbsp;can l solve&nbsp;this&nbsp;situation?
Thank&nbsp;you&nbsp;again&nbsp;for&nbsp;your&nbsp;many&nbsp;answers.

**Comment by atpham88** [comment]
I cannot see the picture you attached or your questions, could you try again?

**Comment by zhangjiajunjiajun** [comment]
Thank you very much for replying to my message, here are my questions:
First of all, in the main.py file, "NonNegativeReals" is marked in red in the code, indicating an error and no definition, but when I run the program earlier, no error is reported.

Secondly, when I run 60% electric + 40% hydrogen, in the result, the battery gen all stations, battery inflow all stations, battery SOC all stations and solar gen all stations are all zero, is this correct?
Finally, thank you again for your help!
If you did not receive my question or did not understand my question, please contact me again, thank you very much!

**Comment by zhangjiajunjiajun** [comment]
I have resent the question I asked you, if you received it, please help me solve it, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "atpham88/HDV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月14日(星期天) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [atpham88/HDV] Ask questions about HDV (Issue #2)





 
I cannot see the picture you attached or your questions, could you try again?
